### ISSUE TITLE
Payment is not working

### ISSUE THREAD

**Issue by kovacsdongo** [szelpe/woocommerce-barion#42]
I have a webshop: https://steeldecor.hu/, but i Can not pay via barion: 3.3.0 – Installed version not tested with active version of WooCommerce 4.6.0

**Comment by szelpe** [comment]
Thanks for reporting the issue, it's going to be fixed in the net version

**Comment by ImrePem** [comment]
I have a similar problem. When I click on the "pay with barion" button, at the checkout page, it jumps to the top, saying "error while processing payment. Please try again later"
In woocommerce logs I see the following: 
10-20-2020 @ 19:50:26 - PreparePayment failed. Errors array: [{"ErrorCode":"AuthenticationFailed","Title":"User authentication failed.","Description":"The login information provided is incorrect. There is no such user in the system or the password is incorrect."}]

Is this the same problem?

**Comment by andreianus** [comment]
I also have the same problem:
WC_Abstract_Legacy_Order::get_product_from_item is deprecated since version 4.4.0! Use $item->get_product() instead.

See this file:
\wp-content\plugins\pay-via-barion-for-woocommerce\includes\class-wc-gateway-barion-request.php

110 $product = $order->get_product_from_item($item);

Maybe this is the problem. (?)

Please repair it.

**Comment by JanProsek** [comment]
Hi @szelpe, is there any improvement in this issue. I have the same "Error while processing payment. Please try again later" while I use Barion test environment and press "Continue to Barion". Is there any solution? Thanks.

**Comment by szelpe** [comment]
Hi @JanProsek,

This issue is resolved in version 3.4.0, if you have an issue with payment, that must be a different one.

Please every time you encounter an issue please check the WooCommerce > Status > Logs to see if there is any error message. Without that there is essentially no way to tell what the issue is.
